### ISSUE TITLE
Project is listed as "HTML" project?

### ISSUE THREAD

**Issue by joergkurtwegner** [wengong-jin/chemprop#13]
A minor thing, but the project is listed as "HTML" project.
Maybe you want to change this to a more sensible category, e.g. Python? :P

**Comment by swansonk14** [comment]
Are you referring to wengong-jin/chemprop or swansonk14/chemprop? I'm pretty sure wengong-jin/chemprop is listed as Python. Unfortunately it seems like swansonk14/chemprop is listed as HTML because we're using a chemical drawing library for our web interface which has a lot of HTML code. Do you know if there's any way to override github and tell it to list it as a Python project instead of an HTML project?
