### ISSUE TITLE
adding partial charges

### ISSUE THREAD

**Issue by joergkurtwegner** [wengong-jin/chemprop#9]
modify featurization.py

```
7a8,10
> from rdkit.Chem.rdPartialCharges import *
> from rdkit.Chem import ChemicalFeatures
> import os
34,35c37,39
< # len(choices) + 1 to include room for uncommon values; + 2 at end for IsAromatic and mass
< ATOM_FDIM = sum(len(choices) + 1 for choices in ATOM_FEATURES.values()) + 2
---
> # len(choices) + 1 to include room for uncommon values; + 3 at end for IsAromatic and mass and partial charge
> ATOM_FDIM = sum(len(choices) + 1 for choices in ATOM_FEATURES.values()) + 3
94c98,99
<            [atom.GetMass() * 0.01]  # scaled to about the same range as other features
---
>            [atom.GetMass() * 0.01] + \
>            [float(atom.GetProp("_GasteigerCharge"))]
192a198,201
> 
>         #assign partial charges
>         ComputeGasteigerCharges(mol)
>         #iterate over atoms
```

**Comment by swansonk14** [comment]
Thank you for the suggestion. We have deprecated this repo in favor of https://github.com/swansonk14/chemprop, but we plan to add partial charge as a feature in the near future.

**Comment by yangkevin2** [comment]
Hi, 

I tried the suggested change on bace, freesolv, and delaney random splits over 10 folds and it made no difference in performance. In addition, the features caused the model to get nans on several datasets I tested (tox21, lipo, sider), since I guess the partial charges computation might not work sometimes? Anyway since it makes no difference in performance I'm going to close the issue and not push this change for now. Thank you for the suggestion though; it was definitely worth a try.
